######################################################################
# Automatically generated by qmake (3.0) Mon Aug 7 17:26:00 2017
######################################################################

TEMPLATE = app
TARGET =  pixelate
INCLUDEPATH += .
QT += gui widgets

# Input
SOURCES += mainwindow.cpp pixelwidget.cpp

HEADERS += \
    pixelwidget.hpp
